### ISSUE TITLE
Can't compile Bidmachine on m1 mac for iOS simulator

### ISSUE THREAD

**Issue by n3ir0** [bidmachine/BidMachine-iOS-SDK#40]
xcode error:
Pods/BidMachine/BidMachine.framework/BidMachine(BDMRetryTimer.o), building for iOS Simulator, but linking in object file built for iOS, file '/Pods/BidMachine/BidMachine.framework/BidMachine' for architecture arm64

**Comment by AssasinSC** [comment]
https://support.apple.com/en-us/HT211861
Use open with rosetta
